-- AlterTable
ALTER TABLE "Advertiser" ALTER COLUMN "direct_client_ind" DROP NOT NULL,
ALTER COLUMN "next_addr_no" DROP NOT NULL,
ALTER COLUMN "tax_reg_number" DROP NOT NULL,
ALTER COLUMN "bsar_no" DROP NOT NULL,
ALTER COLUMN "no_of_changes" DROP NOT NULL,
ALTER COLUMN "clnt_ledger_chg" DROP NOT NULL,
ALTER COLUMN "echo_file_yn" DROP NOT NULL,
ALTER COLUMN "advt_ref" DROP NOT NULL,
ALTER COLUMN "acct_mngr_posn_code" DROP NOT NULL,
ALTER COLUMN "planner_posn_code" DROP NOT NULL,
ALTER COLUMN "next_ordr_no" DROP NOT NULL,
ALTER COLUMN "creation_datestamp" DROP NOT NULL,
ALTER COLUMN "chg_ind" DROP NOT NULL,
ALTER COLUMN "caria_file_yn" DROP NOT NULL,
ALTER COLUMN "external_ref_text" DROP NOT NULL,
ALTER COLUMN "inc_holdings" DROP NOT NULL,
ALTER COLUMN "group_no" DROP NOT NULL,
ALTER COLUMN "schd_create_basis" DROP NOT NULL,
ALTER COLUMN "override_demo_rest_yn" DROP NOT NULL,
ALTER COLUMN "schd_create_basis_nm" DROP NOT NULL,
ALTER COLUMN "company_reg_no" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Agency" ALTER COLUMN "next_addr_no" DROP NOT NULL,
ALTER COLUMN "tax_reg_number" DROP NOT NULL,
ALTER COLUMN "posting_method" DROP NOT NULL,
ALTER COLUMN "no_of_changes" DROP NOT NULL,
ALTER COLUMN "clnt_ledger_chg" DROP NOT NULL,
ALTER COLUMN "echo_file_yn" DROP NOT NULL,
ALTER COLUMN "chg_ind" DROP NOT NULL,
ALTER COLUMN "caria_file_yn" DROP NOT NULL,
ALTER COLUMN "external_ref_text" DROP NOT NULL,
ALTER COLUMN "inc_holdings" DROP NOT NULL,
ALTER COLUMN "group_no" DROP NOT NULL,
ALTER COLUMN "schd_create_basis" DROP NOT NULL,
ALTER COLUMN "override_demo_rest_yn" DROP NOT NULL,
ALTER COLUMN "schd_create_basis_nm" DROP NOT NULL,
ALTER COLUMN "company_reg_no" DROP NOT NULL;
